### PR TITLE
Visualization script update

### PR DESCRIPTION
**Pull request by CedricHerzog**
- Adds a python3 version of the visualization script
- Applies the PeP8 code style convention: https://www.python.org/dev/peps/pep-0008/
- Remove unused var

- Adds a requirements file to facilitate the installation

This script was tested briefly but seems to run ok

### CODE REVIEW

**Comment by mxmssh** [comment]
Hi Cedric, thank you for your contribution!

Would it make more sense to apply these changes the original script instead of creating a new file? Python2 is deprecated and I believe there is no need to support it anymore.

**Comment by CedricHerzog** [comment]
Hi, thank you for your tool :-)

Yes, it could be better to go fully to python 3.
But, as I had no tests to run on it, I chose to keep the python 2 version also.

If you have written tests to check that there are no regressions, it is possible to apply the changes in the original script.

**Comment by mxmssh** [comment]
LGTM, thank you for the commit!

**Comment by mxmssh** [comment]
I think the problem is this difference between correct and incorrect log printing:
Before it was
```
4: ~~1412~~ MSVCR120.dll!printf
4:     arg 0: done
4:  (type=char*, size=0x0)
```
after
```
4: ~~2952~~ MSVCR120.dll!printf
4:     arg 0: done (type=char*, size=0x0)
```

You can just change expected output regex in the test to reflect the new way of printing. It is here
https://github.com/mxmssh/drltrace/blob/94dc91107dcf10a99a715947494f38c6de11e6b0/drltrace_src/CMakeLists.txt#L465
You need to remove \n after done.

**Pull request merged**
